# Generated by Django 3.1.6 on 2021-04-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20210425_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='anonymus',
            field=models.AutoField(default=869868, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
